### ISSUE TITLE
getting errors 

### ISSUE THREAD

**Issue by mnbhaker** [maldinipunisher/telegram-add-member#1]
D:\telegram m\new\New folder\telegram-add-member-main>python get-group.py
D:\telegram m\new\New folder\telegram-add-member-main\get-group.py:36: DeprecationWarning: There is no current event loop
  loop = asyncio.get_event_loop()
Please enter your phone (or bot token): +50947245656
Please enter the code you received: 50247
Signed in successfully as Jmaica
Traceback (most recent call last):
  File "D:\telegram m\new\New folder\telegram-add-member-main\get-group.py", line 37, in <module>
    loop.run_until_complete(main())
  File "C:\Users\manish\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "D:\telegram m\new\New folder\telegram-add-member-main\get-group.py", line 27, in main
    with open(path, 'w') as f :
FileNotFoundError: [Errno 2] No such file or directory: 'group/+62859180449392.json'

Auto Invite
1. Kualitas
2. Kuantitas
Masukkan pilihan invite: 1
D:\telegram m\new\New folder\telegram-add-member-main\main.py:79: DeprecationWarning: There is no current event loop
  loop = asyncio.get_event_loop()
Traceback (most recent call last):
  File "D:\telegram m\new\New folder\telegram-add-member-main\main.py", line 80, in <module>
    loop.run_until_complete(main())
  File "C:\Users\manish\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "D:\telegram m\new\New folder\telegram-add-member-main\main.py", line 23, in main
    members = json.load(open('user/' + clientcfg['PHONE_NUMBER'] + '.json'))
FileNotFoundError: [Errno 2] No such file or directory: 'user/+62859180449392.json'

**Comment by maldinipunisher** [comment]
Your can create new folder **group**, **user** let me know after that.
